version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    working_directory: ~/docker_django_sns/myproject
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: docker-compose up
          command: |
            docker-compose -f myproject/docker-compose.yml build